name: Release Canary Version

on:
  push:
    branches:
      - build/ci
      - ci/*

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Cache npm cache 📦
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: |
            ~/.npm
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci
